objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tech_firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech firm</label>
        <referenceTo>Tech_firm__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Tech_firm__c.object
<CustomObject>
    <label>Tech firm</label>
    <nameField>
        <label>Tech firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tech firms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Max_salary__c</fullName>
        <label>Max salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_salary__c</fullName>
        <label>Min salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/EmployeeHandler.cls
public class EmployeeHandler {
    
    public static void getminandmax(List<Employee__c> emplist , MAp<Id , Employee__c> oldempmap){
        
        Set<Id> techfirmIds = new Set<Id>();
        List<Tech_firm__c> tflisttoupdate = new List<Tech_firm__c>();
        
        
        for(Employee__c emp : emplist){
            if(emp.Tech_firm__c != null){
                if(oldempmap != null){
                    Employee__c oldemp = oldempmap.get(emp.Id);
                    if(emp.Tech_firm__c != oldemp.Tech_firm__c){
                        techfirmIds.add(emp.Tech_firm__c);
                        techfirmIds.add(oldemp.Tech_firm__c);
                    }else{
                        techfirmIds.add(emp.Tech_firm__c);
                    }
                }else{
                    techfirmIds.add(emp.Tech_firm__c);
                }
            }
        }  
        if(!techfirmIds.isempty()){
            List<AggregateResult> results = [select Tech_firm__c techId , min(salary__c) minsal , max(salary__c) maxsal from Employee__c where Tech_firm__c IN :techfirmIds 
                                             Group By Tech_firm__c];
            
            if(!results.isempty()){
                for(AggregateResult agr : results){
                    Tech_firm__c tf = new Tech_firm__c();
                    tf.Id = (Id)agr.get('techId');
                    tf.Min_salary__c = (Decimal)agr.get('minsal');
                    tf.Max_salary__c = (Decimal)agr.get('maxsal');
                    tflisttoupdate.add(tf);
                    
                    
                }
                
                if(!tflisttoupdate.isempty()){
                    update tflisttoupdate;
                }
            }
        }
    }

}